name: Deploy node js application to hostinger

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout code 
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: root
          # key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            cd cicd-pipeline
            git pull origin master
            npm install
            pm2 restart cicd-app || pm2 start index.js --name cicd-app


